application:
  applicationName: demo
  namespaceOverride: prod
  deployment:
    image:
      repository: nginx
      tag: "1.25.0"

  configMap:
    enabled: true
    files:
      config: 
        index.html: |-
          <!DOCTYPE html>
          <html>
          <head>
          <title>dev</title>
          </head>
          <body>

          <h1>dev</h1>

          </body>
          </html>
    
