onechart:

  image:
    repository: nginx
    tag: 1.25.3

  volumes:
    - name: index
      fileName: index.html
      path: /usr/share/nginx/html
      fileContent: |-
        <!DOCTYPE html>
        <html>
        <head>
        <title>dev</title>
        </head>
        <body>

        <h1>dev</h1>

        </body>
        </html>
